
services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:16
    container_name: consorcio_hub_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin123}
      POSTGRES_DB: ${POSTGRES_DB:-consorcio_hub}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - consorcio-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-admin}"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  # Backend NestJS
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: consorcio_backend
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DATABASE_URL=postgresql://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-admin123}@postgres:5432/${POSTGRES_DB:-consorcio_hub}
      - JWT_SECRET=${JWT_SECRET:-tu_jwt_secret_seguro}
      - PORT=3000
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:8083}
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    networks:
      - consorcio-network

  # PgAdmin para administrar la base de datos
  pgadmin:
    image: dpage/pgadmin4
    container_name: consorcio_hub_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin123}
    ports:
      - "5051:80"
    networks:
      - consorcio-network

  # N8n para automatización (comentado temporalmente)
  # n8n:
  #   image: n8nio/n8n:latest
  #   container_name: consorcio_n8n
  #   restart: always
  #   ports:
  #     - "5678:5678"
  #   environment:
  #     - N8N_HOST=${N8N_HOST:-localhost}
  #     - N8N_PORT=5678
  #     - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
  #     - NODE_ENV=production
  #     - WEBHOOK_URL=${WEBHOOK_URL:-http://localhost:5678/}
  #   volumes:
  #     - n8n-data:/home/node/.n8n
  #   networks:
  #     - consorcio-network

networks:
  consorcio-network:
    driver: bridge

volumes:
  postgres_data:
    external: true
    name: backend_postgres_data
  # n8n-data: # Comentado temporalmente
